### ISSUE TITLE
[Bug] Can't start Witchaven with witchavengdx.ini

### ISSUE THREAD

**Issue by BreakinBenny** [atsb/NuBuildGDX#14]
Hi! For some reason, NuBuildGDX doesn't let me play Witchaven anymore, and trying to run the game with the NuBuildGDX executable outside the game directory doesn't even show me any front-end for it.

How can I fix this? Or can you make an error prompt show in case it fails to load?

EDIT: Never mind, I just had to delete the witchavengdx.ini and log

**Comment by BreakinBenny** [comment]
You may want to have some error notification show in case the INI file fails to load in cases like this, @atsb...
I'll provide mine to show what I mean:
[witchavengdx.ini.txt](https://github.com/user-attachments/files/18211751/witchavengdx.ini.txt)

This also seems to affect TekWar.

**Comment by atsb** [comment]
> You may want to have some error notification show in case the INI file fails to load in cases like this, @atsb... I'll provide mine to show what I mean: [witchavengdx.ini.txt](https://github.com/user-attachments/files/18211751/witchavengdx.ini.txt)
> 
> This also seems to affect TekWar.

Thanks for the suggestion, I will do that.
