### ISSUE TITLE
[Feature Request] Raw Input

### ISSUE THREAD

**Issue by Patrxgt** [atsb/NuBuildGDX#2]
Hello. It would be very nice, if you could provide a raw input option. Mouse input in Java-based apps feels laggy at times and different Java-based games (eg. Minecraft) fixed that by implementing raw input support.

**Comment by atsb** [comment]
rawinput in handled with awt.Robot as part of the mouse movement.

I don't get any stuttery mouse movements anymore on both my mice (low-dpi or high dpi).  It is buttery smooth for me.

**Comment by atsb** [comment]
Try using the latest Nightly build in the releases tab.  I've added native libs for jinput-raw and upgraded jinput's library to allow better support for raw input.

**Comment by Patrxgt** [comment]
It's definitely better now.
