### ISSUE TITLE
Very "stuttery" mouse movement when using Polymost

### ISSUE THREAD

**Issue by Patrxgt** [atsb/NuBuildGDX#3]
When using Polymost renderer, game starts to act, like it can't process all of the mouse input and in result camera movement becomes very "jittery" or it stops moving altogether.

**Comment by atsb** [comment]
And without using Polymost?

**Comment by atsb** [comment]
I tried it with one of my other mice and yeah I got it also with that one.  Probably something with how it uses the mouse input on the renderer vs direct mouse input on Classic renderer

**Comment by Patrxgt** [comment]
> And without using Polymost?

Without Polymost it works even better, than in the OG BuildGDX.

**Comment by Patrxgt** [comment]
> I tried it with one of my other mice and yeah I got it also with that one. Probably something with how it uses the mouse input on the renderer vs direct mouse input on Classic renderer

Maybe Polymost doesn't like high DPIs or Polling Rates?

**Comment by atsb** [comment]
> > And without using Polymost?
> 
> Without Polymost it works even better, than in the OG BuildGDX.

I spent a lot of time fixing the Classic renderer, seems I need to give Polymost a bit of a makeover also.  I'll focus on that.

I think you might be right there.  Using my barebones logitec pebble, Polymost is fine, then when switching to a Razor gaming mouse with high DPI settings, it stutters and goes bananas.

**Comment by atsb** [comment]
I've done a few things locally and am testing some things that hopefully have this in better shape

**Comment by DarthRazdor** [comment]
I have this problem too. It's very uncomfortable to play Witchaven 2. Is there any chance to see a fix?

**Comment by atsb** [comment]
This should be fixed now, I get no stutters at all.

**Comment by atsb** [comment]
Polymost removed in 1.19.0
