### ISSUE TITLE
Crash on Game Launch (BadWindow) On Linux

### ISSUE THREAD

**Issue by d10sfan** [atsb/NuBuildGDX#4]
I'm using 1.18.1 from the releases tab, and I'm running inside Wayland  or x11 (and have xwayland installed, other x games work fine).

If I run `java -jar NuBuildGDX.jar`, the launcher works fine and I can pick a game and click Play, the launcher closes and the game does not launch and I get this error in the terminal window:

```
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  20 (X_GetProperty)
  Resource id in failed request:  0x4600007
  Serial number of failed request:  1809
  Current serial number in output stream:  1809
```

This is my java information:

```
java --version
openjdk 11.0.19 2023-04-18
OpenJDK Runtime Environment (build 11.0.19+7)
OpenJDK 64-Bit Server VM (build 11.0.19+7, mixed mode)
```

**Comment by d10sfan** [comment]
Interestingly this also happens on x11 for me so isn't directly related to Wayland

**Comment by atsb** [comment]
Very weird indeed.  I haven't been able to simulate any crashes on the latest JDK's on Linux or WIndows.  What JDK are you all using?  Not sure what this could be related to, the crash logs aren't so detailed but seem to point towards the window icon?

**Comment by d10sfan** [comment]
openjdk 11.0.19 2023-04-18

**Comment by d10sfan** [comment]
Should I be using a different one from that?

**Comment by atsb** [comment]
That should work fine, I'll do some more digging.

**Comment by atsb** [comment]
So the crash happens when glfw attempts to create the window, meaning it crashes inside of glfw.  Not much I can do about that, consider Linux not supported for now.
