### ISSUE TITLE
NuBuildGDX won't launch (Windows 10)

### ISSUE THREAD

**Issue by AJOgames** [atsb/NuBuildGDX#5]
Whenever I try to launch NuBuildGDX, I don't get anything, no window pops up like the original BuildGDX, I have Java fully updated, so it couldn't be the problem. am I doing something wrong, or is this for Windows 11 exclusively?

**Comment by FrostedMoontips** [comment]
Weirdly enough I've been having this issue too but on Windows 11. 
Tried moving it to different hard drives but no use, strange cus it used to work just fine?

**Comment by atsb** [comment]
I'll give it a try too, this is a bit weird as nothing has really changed at all

**Comment by atsb** [comment]
Should be fine now, I've updated the release with a new file

**Comment by FrostedMoontips** [comment]
Awesome, I'll go ahead and test it real quick

EDIT: Yup, it launches now :D

**Comment by atsb** [comment]
Fixed in 1.19.0
