### ISSUE TITLE
NuBuildGDX refuses to boot up any games

### ISSUE THREAD

**Issue by morganfreem** [atsb/NuBuildGDX#6]
![error](https://github.com/atsb/NuBuildGDX/assets/144499976/c8dd0790-28ca-4357-95ce-f800887f66d9)
Yep, seems like it's a window problem? I'm not sure, but it doesn't only happen with Duke Nukem 3D, I wonder what's the problem, I'm using Arch Linux, Linux-Zen 6.7.6 as the kernel.

**Comment by atsb** [comment]
Linux isn't supported due to a problem with GDX.
