### ISSUE TITLE
How does this work?

### ISSUE THREAD

**Issue by Solar8610** [atsb/NuBuildGDX#8]
I know BuildGDX, you Download it, Unpack it and Start it. 
You download NuBuildGDX, Unpack it and then ?? 
How and where do I install it ? How do I start it ? 
Please help!!

**Comment by atakanbaba3161** [comment]
ı still try to figure it out ? did you find anything

**Comment by atsb** [comment]
I have rebuilt it with Java 11 with Java 8 language level.  Using the jar file works fine for me and loads everything without issues on Windows 11.

I've made it into a wrapped .exe file so those without a JDK or JRE installed should have no issues.
